---

- name: Set the firewall rules
  include_tasks: ufw-rules.yml

- name: Remove root password access from SSH
  when: security.ssh_disable_root_access_with_password
  tags: security
  notify: Restart SSH
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin yes'
    replace: 'PermitRootLogin without-password'
    mode: 0600

- name: Lock root account
  tags: security
  user:
    name: root
    password_lock: '{{ security.lock_root_password }}'

# These tasks are configuring the system to give access
# to some administrators, without having to logon as root.
# You need to define a public SSH key for each user.
# see example YAML file
- name: Add SSH keys for the administrators
  register: administrators
  authorized_key:
    user: '{{ user.uid }}'
    state: present
    key: >-
      {{ user.ssh_key.type }}
      {{ user.ssh_key.data | regex_replace(" ") }}
      {{ user.ssh_key.comment }}
  with_items:
    - '{{ users | selectattr("ssh_key", "defined") | list }}'
  loop_control:
    loop_var: user

- name: Install the sudo package
  when: users | selectattr("ssh_key", "defined") | list != []
  apt:
    name: sudo
    state: latest

- name: Add thes administrators to the sudo group
  when: users | selectattr("ssh_key", "defined") | list != []
  user:
    name: '{{ user.uid }}'
    groups:
      - sudo
  with_items:
    - '{{ users | selectattr("ssh_key", "defined") | list }}'
  loop_control:
    loop_var: user
