---

- name: Get the external IP address
  delegate_to: localhost
  register: ext_ip
  shell: >-
    curl -s https://api.ipify.org/
  args:
    warn: false

- name: Make sure the external IP address is working as well
  tags: security
  ufw:
    proto: tcp
    port: 22
    src: '{{ ext_ip.stdout }}'
    rule: allow
    comment: Access SSH from the ansible host (IPv4)

# This is safe. Is the ansible host has no IPv6
# address, the API returns the IPv4
- name: Get the external IP address (IPv6)
  delegate_to: localhost
  register: ext_ip6
  shell: >-
    curl -s https://api6.ipify.org/
  args:
    warn: false

- name: Make sure the external IP address is working as well
  tags: security
  ufw:
    proto: tcp
    port: 22
    src: '{{ ext_ip6.stdout }}'
    rule: allow
    comment: Access SSH from the ansible host (IPv6)


- name: Configure the firewall for SSH access
  tags: security
  ufw:
    proto: tcp
    port: 22
    src: '{{ access.src }}'
    rule: '{{ access.rule | default("allow") }}'
    comment: '{{ access.comment | default("Allow SSH access") }}'
    state: enabled
  with_items:
    - '{{ firewall.ssh }}'
  loop_control:
    loop_var: access

- name: Configure firewall output default policy
  tags: security
  ufw:
    policy: '{{ firewall.output.policy }}'
    direction: outgoing

- name: Configure firewall output rules
  tags: security
  ufw:
    proto: '{{ access.proto | default("tcp") }}'
    port: '{{ access.port }}'
    dest: '{{ access.dest }}'
    rule: '{{ access.rule | default("allow") }}'
    comment: '{{ access.comment | default("") }}'
    direction: out
  with_items:
    - '{{ firewall.output.rules }}'
  loop_control:
    loop_var: access

- name: Allow external echo requests
  tags: security
  notify: Restart UFW
  lineinfile:
    path: /etc/ufw/before.rules
    line: -A ufw-before-output -p icmp --icmp-type echo-request -j ACCEPT
    insertbefore: COMMIT
