
- name: Restart postfix
  tags: postfix
  service:
    name: '{{ service }}'
    state: restarted
  with_items:
    - postfix
    - postfix@-
  loop_control:
    loop_var: service

- name: Restart AppArmor service
  service:
    name: apparmor
    state: restarted
