---

- name: Create the DNS config into /etc/homebox
  tags: dns
  ini_file:
    path: '/etc/homebox/{{ network.domain }}.ini'
    section: main
    option: provider
    value: gandi
    mode: 0600

- name: Add the keys into the DNS config
  tags: dns
  ini_file:
    path: '/etc/homebox/{{ network.domain }}.ini'
    section: gandi
    option: key
    value: '{{ dns.gandi.key }}'

- name: Add the domain into the DNS config
  tags: dns
  ini_file:
    path: '/etc/homebox/{{ network.domain }}.ini'
    section: main
    option: domain
    value: '{{ network.domain }}'

- name: Copy the dns management script
  tags: dns
  copy:
    src: dns-manager.py
    dest: /usr/local/sbin/dns-manager
    mode: 0700

- name: Run the the dns management script
  tags: dns
  when: dns.update
  shell: >-
    /usr/local/sbin/dns-manager
    --config /etc/homebox/{{ network.domain }}.ini
    --dkim-public-key-file /etc/opendkim/keys/{{ dkim.selector }}.txt
    --auto-discover all
    --log-file /var/log/dns-update-gandi.log
    --log-level {{ system.debug | ternary(DEBUG, INFO) }}
    --test {{ dns.test }}
    --add-wildcard {{ dns.add_wildcard }}
    --add-www {{ website.install }}
