---

- name: Create the autoconfiguration directories
  tags: autoconfig
  file:
    path: /var/www/autoconfig/mail/
    state: directory

- name: Copy autoconfig XML template
  tags: autoconfig
  template:
    src: config-v1.1.xml
    dest: /var/www/autoconfig/mail/config-v1.1.xml
    owner: root
    group: root
    mode: 0644

- name: Create the autoconfig site
  tags: autoconfig
  notify: Restart nginx server
  template:
    src: autoconfig.conf
    dest: '/etc/nginx/sites-available/autoconfig.{{ network.domain }}.conf'
    owner: root
    group: root
    mode: 0644

- name: Ensure autoconfig resolves to localhost
  lineinfile:
    path: /etc/hosts
    line: '127.0.0.1    autoconfig.{{ network.domain }}'

- name: Enable nginx site
  tags: autoconfig
  file:
    src: '/etc/nginx/sites-available/autoconfig.{{ network.domain }}.conf'
    dest: '/etc/nginx/sites-enabled/autoconfig.{{ network.domain }}.conf'
    state: link

# AppArmor configuration ======================================================

- name: Install nginx AppArmor profile
  when: security.app_armor
  tags: autoconfig, security, apparmor
  template:
    src: 'apparmor.d/local/autoconfig'
    dest: '/etc/apparmor.d/local/nginx-autoconfig'

- name: Check if AppArmor nginx configuration already contains the line
  register: line_found
  shell: >-
    grep -c 'include <local/nginx-autoconfig>'
    /etc/apparmor.d/usr.sbin.nginx
  changed_when: false
  failed_when: false

- name: Add autoconfig AppAromor specific configuration
  when: security.app_armor and line_found.stdout == '0'
  tags: autoconfig, security, apparmor
  register: aa_config
  lineinfile:
    path: /etc/apparmor.d/usr.sbin.nginx
    line: '  #include <local/nginx-autoconfig>'
    insertbefore: '# End of local includes for homebox'

- name: Activate AppArmor profiles
  when: security.app_armor and aa_config.changed
  tags: autoconfig, security, apparmor
  command: 'aa-enforce usr.sbin.nginx'
  notify: Restart AppArmor service

# Create entries for the DNS server ===========================================
- name: Generate DNS records for bind
  tags: bind
  when: bind.install
  template:
    src: 60-autoconfig.bind
    dest: /etc/homebox/dns-entries.d/60-autoconfig.bind
