---

- name: Create extra certificates
  include_role:
    name: certificates
    apply:
      tags: certificates
  with_items:
    - '{{ extra_certs | default([]) }}'
  loop_control:
    loop_var: certificate
