---

- name: Install required python packages
  tags: apt
  apt:
    name: python3-psutil
    state: latest

- name: Install borgbackup package
  when:
    - ansible_facts['distribution'] == "Debian"
    - ansible_facts['distribution_major_version'] == "9"
  tags: apt
  apt:
    name: borgbackup
    default_release: stretch-backports
    state: latest

- name: Install borgbackup package
  when:
    - ansible_facts['distribution'] == "Debian"
    - ansible_facts['distribution_major_version']|int >= 10
  tags: apt
  apt:
    name: borgbackup
    state: latest

- name: Create the backups mount point root
  file:
    path: /mnt/backup
    state: directory

- name: Create the directories to import and export the keys
  file:
    path: '{{ path }}'
    state: directory
    mode: 0700
  with_items:
      - /tmp/backup-keys-import
      - /tmp/backup-keys-export
  loop_control:
    loop_var: path

- name: Create the backup config into /etc/homebox
  tags: config
  ini_file:
    path: '/etc/homebox/backup.ini'
    section: 'alerts'
    option: '{{ option.name }}'
    value: '{{ option.value }}'
    mode: '0600'
  with_items:
    - name: from
      value: '{{ backup.alerts.from }}'
    - name: recipient
      value: '{{ backup.alerts.recipient }}'
    - name: jabber
      value: '{{ backup.alerts.jabber }}'
  loop_control:
    loop_var: option

- name: Configure each protocol
  include_tasks: 'install-protocol-{{ location.url | urlsplit("scheme") }}.yml'
  with_items:
    - '{{ backup.locations | default([]) }}'
  loop_control:
    loop_var: location

- name: Add the cron entries to backup the home directory
  tags: config
  template:
    src: cron-backup-script.sh
    dest: '/etc/cron.{{ location.frequency | default("daily") }}/backup-{{ location.name }}'
    mode: '0700'
  with_items:
    - '{{ backup.locations | default([]) }}'
  loop_control:
    loop_var: location

- name: Add the cron entries to check the backup
  register: backup_config
  tags: config
  template:
    src: cron-check-script.sh
    dest: '/etc/cron.{{ location.check_frequency | default("weekly") }}/backup-check-{{ location.name }}'
    mode: '0700'
  with_items:
    - '{{ backup.locations | default([]) }}'
  loop_control:
    loop_var: location

- name: Create a random passphrase for encrypted backup
  tags: encryption
  no_log: true
  set_fact:
    backup_key: '{{ lookup("password", "{{ encryption.backupKeyParams }}") }}'

- name: Save the passphrase
  tags: encryption
  template:
    src: backup-key
    dest: /etc/homebox/backup-key
    owner: root
    group: root
    mode: '0400'

- name: Copy the backup script
  tags: scripts
  copy:
    src: backup.py
    dest: '/usr/local/sbin/homebox-backup'
    mode: '0700'

- name: Create sync directories to import/export keys
  tags: sync
  file:
    path: '{{ path }}'
    state: directory
  with_items:
    -  /tmp/backup-keys-import
    -  /tmp/backup-keys-export
  loop_control:
    loop_var: path

- name: Create the backup keys directory locally if it does not exists
  register: backup_keys_local_directory
  delegate_to: localhost
  tags: sync
  file:
    path: '{{ backup_directory }}/backup-keys/'
    state: directory

# If the folder already existed, upload the keys on the server.
- name: Upload the backup encryption keys if they exists
  when: not backup_keys_local_directory.changed
  tags: sync
  register: keys_restore
  synchronize:
    src: '{{ backup_directory }}/backup-keys/'
    dest: /tmp/backup-keys-import/
    mode: push
    owner: no
    group: no
    perms: yes
    rsync_opts:
      - '--no-motd'
      - '--quiet'

- name: Initialise the repository, to test access and retrieve the key
  when: backup.locations is defined and backup.locations != []
  tags: backup
  shell: >-
    /usr/local/sbin/homebox-backup
    --action init
    --config {{ location.name }}
    --import-key-path /tmp/backup-keys-import/{{ location.name }}.key
    --export-key-path /tmp/backup-keys-export/{{ location.name }}.key
  with_items:
    - '{{ backup.locations }}'
  loop_control:
    loop_var: location

# In this direction, we should overwrite the keys
# in case new ones have been created
- name: Check if new keys have been copied in the export directory
  tags: sync
  register: keys_exported
  find:
    paths: /tmp/backup-keys-export/
    patterns: '*.key'

- name: Retrieve the backup encryption keys on your local machine
  tags: sync
  when: keys_exported.matched > 0
  synchronize:
    mode: pull
    src: /tmp/backup-keys-export/*.key
    dest: '{{ backup_directory }}/backup-keys/'
    perms: yes
    rsync_opts:
      - '--no-motd'
      - '--quiet'

- name: Remove the backup keys directory, we don't need this anymore
  tags: sync
  file:
    path: '{{ path }}'
    state: absent
  with_items:
    -  /tmp/backup-keys-import
    -  /tmp/backup-keys-export
  loop_control:
    loop_var: path

- name: Restore backups from a previous installation
  tags: restore
  when: backup.locations is defined and backup.locations != []
  include_tasks: 'restore-all.yml'
