---

# Default list of development packages to install
# You can override it in your config/system.yml file

# they are installed when running the playbook dev-support,
# and cleaned up when using dev-cleanup

devel:
  packages:
    - mc
    - telnet
    - dnsutils
    - whois
    - tmux
    - pfqueue
    - aptitude
    - man
    - less
    - vim
    - net-tools
    - file
    - swaks
    - curl
    - locate
    - colorized-logs
    - bash-completion
  root:
    shell: /bin/bash
