---

- name: Check if opendmarc has been installed
  tags: apt,opendmarc
  shell: dpkg -s opendmarc
     
- name: Check if the rspamd service is up and running
  tags: systemctl,opendmarc
  shell: systemctl status opendmarc
    
- name: Test opendmarc configuration
  tags: systemctl,opendmarc
  shell: opendmarc-check '{{ network.domain }}'
  become: yes
  become_method: sudo
  become_user: opendmarc
    
