site_name: homebox
pages:
  - Home: index.md
  - Features: features.md
  - Installation: installation.md
  - Wait for DNS propagation: dns-propagation.md
  - Debian preseed: preseed.md
  - Main configuration file: configuration.md
  - Email configuration: email-configuration.md
  - Roundcube Webmail: webmail-roundcube.md
  - Email access monitoring: email-access-monitoring.md
  - Sogo Groupware: groupware-sogo.md
  - Antispam configuration: antispam-rspamd.md
  - Jabber configuration: jabber-configuration.md
  - Gogs configuration: gogs-configuration.md
  - Tor / privoxy configuration: tor-privoxy-configuration.md
  - Security configuration: security-configuration.md
  - Single Packet Authorization: spa-fwknop.md
  - Transmission configuration: transmission-configuration.md
  - DNS Server configuration: bind-configuration.md
  - External accounts: external-accounts.md
  - Backup your emails: backup.md
  - Backup your deployment: deployment-backup.md
  - Monitoring with Zabbix: zabbix.md
  - Maintenance: maintenance.md
  - Testing and development: development.md
  - Code of conduct: codeofconduct.md
theme: readthedocs
