---

- name: Install python apt library
  tags: apt
  apt:
    name: python3-apt
    state: present

# Initialise the packages repository to a standard,
# including backports, contrib and non-free software
- name: Initialise default repositories
  register: repositories
  tags: apt
  template:
    src: sources.list
    dest: /etc/apt/sources.list

- name: Use a proxy if needed
  when: system.apt_cacher != None
  tags: apt
  template:
    src: proxy
    dest: /etc/apt/apt.conf.d/proxy

- name: Make sure no proxy is configured if not needed
  when: system.apt_cacher == None
  tags: apt
  file:
    path: /etc/apt/apt.conf.d/proxy
    state: absent

# Some cloud providers, the cache_valid_time condition
# is not working just after the installation (vultr)
- name: Force the packages cache update on the first installation
  when: repositories.changed
  register: packages_cache
  tags: apt
  apt:
    update_cache: yes

- name: Upgrade the distribution
  when: packages_cache.changed
  tags: apt
  apt:
    upgrade: yes

- name: Install apticron to send email alerts
  tags: apt
  apt:
    name: apticron
    state: present

# Starting from Debian buster (10), /etc/apticron/apticron.conf is not
# installed by default
- name: Check if the apticron configuration file is present
  register: apticron_conf_stat
  stat:
    path: /etc/apticron/apticron.conf

# The default apticron.conf file is available in /usr/lib/apticron
- name: Install distribution default configuration of apticron if not already present
  tags: apt
  when: not apticron_conf_stat.stat.exists
  copy:
    remote_src: yes
    src: /usr/lib/apticron/apticron.conf
    dest: /etc/apticron/apticron.conf

- name: Configure apticron to send email alerts
  tags: apt
  replace:
    path: /etc/apticron/apticron.conf
    regexp: '^#?EMAIL=".*"'
    replace: EMAIL="{{ security.alerts_email | join(' ') }}"
