---

- name: Build the final bind configuration
  tags: config
  notify: Restart bind
  assemble:
    src: '/etc/homebox/dns-entries.d/'
    dest: '/etc/bind/forward.{{ network.domain }}'
    delimiter: '\n'
    regexp: '^.*\.bind$'

- name: Copy DNS entries in bind cache directory (main IP)
  notify: Restart bind
  copy:
    src: '/etc/bind/forward.{{ network.domain }}'
    dest: '/var/cache/bind/forward.{{ network.domain }}'
    owner: bind
    group: bind
    remote_src: true

- name: Copy DNS entries in bind cache directory (reverse for main IP)
  when: bind.generate_reverse
  notify: Restart bind
  copy:
    src: '/etc/bind/reverse-main.{{ network.domain }}'
    dest: '/var/cache/bind/reverse-main.{{ network.domain }}'
    owner: bind
    group: bind
    remote_src: true

- name: Copy DNS entries in bind cache directory (reverse for backup IP)
  notify: Restart bind
  when: bind.generate_reverse and backup_ip is defined and (backup_ip | bool)
  copy:
    src: '/etc/bind/reverse-backup.{{ network.domain }}'
    dest: '/var/cache/bind/reverse-backup.{{ network.domain }}'
    owner: bind
    group: bind
    remote_src: true
