---

################################################################################
# Get the external IP address, from configuration file,
# Check if a backup IP address is used
# Detect both types of IP addresses
# Detect if IPv6 is used
################################################################################

# First IP address, mandatory
- name: Store the extenal IP address specified manually
  tags: facts
  set_fact:
    external_ip: '{{ network.external_ip }}'

- name: Set external IP address type (A or AAAA)
  tags: facts
  set_fact:
    external_ip_type: '{{ external_ip | ipv6 | ternary("AAAA", "A") }}'

# Backup IP address if defined
- name: Get the backup IP address
  when: network.backup_ip != None
  tags: facts
  set_fact:
    backup_ip: '{{ network.backup_ip }}'

- name: Set backup IP address type (A or AAAA)
  tags: facts
  when: network.backup_ip != ""
  set_fact:
    backup_ip_type: '{{ backup_ip | ipv6 | ternary("AAAA", "A") }}'

- name: Check and remember if IPv6 is used
  set_fact:
    ipv6_used: >-
      backup_ip_type == "AAAA" or
      external_ip_type == "AAAA"
