---

- name: Install the required packages
  tags: apt
  vars:
    pkgs:
      - busybox
      - dropbear
      - dropbear-initramfs
  apt:
    update_cache: true
    name: '{{ pkgs }}'
    state: latest

- name: Copy the ssh public key for authentication
  copy:
    src: /root/.ssh/authorized_keys
    dest: /etc/dropbear-initramfs/authorized_keys
    remote_src: yes

- name: Remove dropbear default keys
  file:
    path: /etc/dropbear-initramfs/{{ key }}
    state: absent
  with_items:
      - dropbear_ecdsa_host_key
      - dropbear_rsa_host_key
      - dropbear_dss_host_key
  loop_control:
    loop_var: key

- name: Convert the openssh key already existing for dropbear
  notify: Update initramfs
  shell: >-
    /usr/lib/dropbear/dropbearconvert openssh dropbear
    /etc/ssh/{{ key.src }} /etc/dropbear-initramfs/{{ key.dest }}
  args:
    creates: '/etc/dropbear-initramfs/{{ key.dest }}'
  with_items:
    - '{{ keys_convert }}'
  loop_control:
    loop_var: key

- name: Convert the openssh key already existing for dropbear
  notify: Update initramfs
  shell: >-
    /usr/lib/dropbear/dropbearconvert openssh dropbear
    /etc/ssh/{{ key.src }} /etc/dropbear/{{ key.dest }}
  args:
    creates: '/etc/dropbear/{{ key.dest }}'
  with_items:
    - '{{ keys_convert }}'
  loop_control:
    loop_var: key
