---

- name: Create a unique subject for testing
  tags: postfix
  set_fact:
    test_subject: "Test email {{ lookup( 'password', '/dev/null length=32' ) | to_uuid }}"

- name: Create an email template
  tags: postfix
  template:
    src: check/testmsg-01.txt
    dest: /tmp/testmsg-01.txt
    mode: '0600'
    owner: postfix
    group: postfix

- name: Send an email to an email address with unicode characters
  tags: postfix
  shell: >-
    swaks
    --from="{{ users[0].mail }}"
    --to "{{ users[1].aliases[0] }}"
    --h-Subject '{{ test_subject }}'
    -tls --tls-verify
    --auth
    --auth-user="{{ user0_uid }}"
    --auth-password="{{ user0_password }}"
    --server smtp.{{ network.domain }}
    --body /tmp/testmsg-01.txt
  become: yes
  become_method: sudo
  become_user: postfix

- name: Check if the email has been received
  tags: postfix
  register: email_found
  shell: >-
    grep -l "Subject: {{ test_subject }}"
    /home/users/{{ users[1].uid }}/mails/maildir/new/*
  changed_when: false
  until: email_found.rc == 0
  retries: 10
  delay: 2
