---

- name: Configure the firewall for SSH access
  tags: security
  ufw:
    proto: '{{ access.proto | default("tcp") }}'
    port: '{{ access.port | default(22) }}'
    src: '{{ access.src }}'
    rule: '{{ access.rule | default("allow") }}'
    comment: '{{ access.comment | default("Allow SSH access") }}'
    state: enabled
  with_items:
    - '{{ firewall.ssh }}'
  loop_control:
    loop_var: access

- name: Configure firewall output default policy
  tags: security
  ufw:
    policy: '{{ firewall.output.policy }}'
    direction: outgoing

- name: Configure firewall output rules
  tags: security
  ufw:
    proto: '{{ access.proto | default("tcp") }}'
    port: '{{ access.port }}'
    dest: '{{ access.dest }}'
    rule: '{{ access.rule | default("allow") }}'
    comment: '{{ access.comment | default("") }}'
    direction: out
  with_items:
    - '{{ firewall.output.rules }}'
  loop_control:
    loop_var: access

- name: Allow external echo requests
  tags: security
  notify: Restart UFW
  lineinfile:
    path: /etc/ufw/before.rules
    line: -A ufw-before-output -p icmp --icmp-type echo-request -j ACCEPT
    insertbefore: COMMIT
