---

# Uninstall Zabbix server
- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/../config/defaults.yml'
  roles:
    - role: zabbix-server
      tags: uninstall

- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/../config/defaults.yml'
  vars:
    certificate:
      type: zabbix
  roles:
    - certificates
