---

# These rules are included in numeric order,
# to generate the final firewall rules set.
rule_files:
  - '00-init'
  - '10-base'
  - '10-outbound'
  - '20-proxy'
  - '20-trusted-networks'
  - '25-banned-networks'
  - '40-in-dns'
  - '90-close'
