---

- name: Check if the file exists
  register: cleanup_file
  stat:
    path: '{{ cleanup_path }}'
  tags: cleanup

- name: Unlock and remove vultr specific file
  when: cleanup_file.stat.exists
  block:
    - name: unlock the file
      file:
        path: '{{ cleanup_path }}'
        attr: -i
        force: yes
    - name: Remove cloud init log readers
      notify: Reload systemd
      file:
        path: '{{ cleanup_path }}'
        state: absent
  tags: cleanup
