# LDAP configuration
ldap:
  hostname: 'ldap.{{ network.domain }}'
  organization:
    domain: '{{ network.domain }}'
    base: 'dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  users:
    dn: 'ou=users,dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  groups:
    dn: 'ou=groups,dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  manager:
    uid: manager
    dn: 'cn=manager,ou=users,dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  readonly:
    uid: readonly
    dn: 'cn=readonly account,ou=users,dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  admin:
    dn: 'cn=admin,dc={{ network.domain | regex_replace("\.", ",dc=") }}'
    desc: administrator account


# User storage quotas for email
quota:
  per_user: '{{ mail.quota.default }}'
  listener:
    port: '{{ mails_quota_port }}'

