---
# Various cleanup tasks before the system goes live

- name: Include common cleanup tasks
  include_tasks: cleanup-common.yml

- name: Include bind related cleanup tasks
  when: bind.install
  include_tasks: network-bind.yml

# At this point, it might be necessary to reboot
# To reload all bash instances
