---

- name: Create the emails migration and imports folders
  file:
    path: '{{ path }}'
    owner: '{{ user.uid }}'
    group: users
    state: directory
    mode: 0700
  with_items:
    - '/home/users/{{ user.uid }}/mails/import/safe'
    - '/home/users/{{ user.uid }}/mails/import/conf'
  loop_control:
    loop_var: path

- name: Create a migration file for each account
  template:
    src: 'isync/{{ account.type }}.conf'
    dest: '/home/users/{{ user.uid }}/mails/import/conf/{{ account.name }}-{{ account.type }}.conf'
    owner: '{{ user.uid }}'
    group: users
    mode: 0600
  with_items:
    - '{{ user.external_accounts | default([]) }}'
  loop_control:
    loop_var: account

- name: Encrypt each configuration file using the server's passphrase and place them in the safe
  command: >-
    openssl aes-256-cbc
    -in /home/users/{{ user.uid }}/mails/import/conf/{{ account.name }}-{{ account.type }}.conf
    -out /home/users/{{ user.uid }}/mails/import/safe/{{ account.name }}-{{ account.type }}.conf
    -pass file:/etc/homebox/system-key
  with_items:
    - '{{ user.external_accounts | default([]) }}'
  loop_control:
    loop_var: account

- name: Change the owner to the user
  file:
    path: '/home/users/{{ user.uid }}/mails/import/safe/{{ account.name }}-{{ account.type }}.conf'
    owner: '{{ user.uid }}'
    group: users
    mode: 0600
  with_items:
    - '{{ user.external_accounts | default([]) }}'
  loop_control:
    loop_var: account

- name: Remove the clear text version
  file:
    path: '/home/users/{{ user.uid }}/mails/import/conf/{{ account.name }}-{{ account.type }}.conf'
    state: absent
  with_items:
    - '{{ user.external_accounts | default([]) }}'
  loop_control:
    loop_var: account
