---

- name: Do not allow SSH from root with a password
  notify: Restart SSH
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin yes'
    replace: 'PermitRootLogin without-password'
    mode: '0600'

- name: Lock the root account
  user:
    name: root
    password_lock: '{{ security.lock_root_password }}'

- name: Remove users password access from SSH
  notify: Restart SSH
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication yes.*'
    replace: 'PasswordAuthentication no'
    mode: '0600'

- name: Custom SSH server setting
  template:
    src: ssh/sshd.conf
    dest: /etc/ssh/sshd_config.d/homebox.conf
    mode: 0644
