---

# Remove packages that are not needed for a live system:
# bash-completion:
# See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=825153
# this seems to remove most errors like :
# <passwd="*"> request denied by validnames option.
- name: Remove useless packages
  tags: apt
  apt:
    name: '{{ cleanup_packages }}'
    state: absent
    autoremove: true
    purge: yes

- name: Cleanup packages cache
  apt:
    autoclean: true
    autoremove: true

# SSH and remote access cleanup
- name: Check if some users are configured with remote access
  set_fact:
    remote_user_access: '{{ users | selectattr("ssh_key", "defined") | list != [] }}'

# The next task will completely disable the remote access with SSH and root,
# only if these two conditions are meet:
# - some users are configured to connect through SSH and they ssh key is defined
# - the flag 'security.ssh_disable_root_access' has been set to true
- name: Completely disable root SSH login
  when:
    - remote_user_access
    - security.ssh_disable_root_access
  tags: security
  notify: Restart SSH
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin without-password'
    replace: 'PermitRootLogin no'
    mode: '0600'

# The external IP address detection tasks is creating these two files
# Remove them, so we can run the script again if the IP address(es) changes
- name: Remove cached external IP addresses
  file:
    path: '{{ path }}'
    state: absent
  loop:
    - /tmp/external_ip.txt
    - /tmp/backup_ip.txt
  loop_control:
    loop_var: path
