---

- name: deploy the template to update resolv.conf
  template:
    src: resolv.conf
    dest: /etc/resolv.conf

# Check if a DHCP client is installed. In this case,
# make sure it is not querying the external DNS servers
- name: Check if dhclient is installed
  register: dhclient_config
  stat:
    path: /etc/dhcp/dhclient.conf

- name: Disable DNS server updates in dhclient configuration file
  when: dhclient_config.stat.isreg
  template:
    src: dhclient.conf
    dest: /etc/dhcp/dhclient.conf

- name: Remove isc-dhcp-client debug file
  file:
    path: /etc/dhcp/dhclient-exit-hooks.d/debug
    state: absent
