---

- name: Install clamav antivirus suite
  apt:
    name: '{{ pkg }}'
    state: latest
  with_items:
    - clamav
    - clamav-base
    - clamav-daemon
    - clamav-freshclam
    - clamdscan
    - clamsmtp
    - ipcalc
  loop_control:
    loop_var: pkg

- name: Set up the configuration file
  notify: Restart clamav services
  template:
    src: clamsmtpd.conf
    dest: /etc/clamsmtpd.conf

###############################################################################
# See the Debian bug report:
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=827909
#
- name: Start clamav freshclam service
  register: clamav_freshclam
  service:
    name: clamav-freshclam
    state: started
    enabled: yes

- name: Wait for the freshclam service to have downloaded daily.cvd
  register: clamav_freshclam
  wait_for:
    path: /var/lib/clamav/daily.cvd
    sleep: 1
    timeout: 60

- name: Start clamav service
  service:
    name: clamav-daemon
    state: started
    enabled: yes

- name: Wait for the clamav service to be started
  register: clamav_daemon
  command: systemctl status clamav-daemon
  retries: 10
  until: clamav_daemon.rc == 0
  delay: 1

#
###############################################################################

- name: Get the remote locale
  tags: locale
  set_fact:
    lang: '{{ ansible_env.LANG | regex_replace("\..*", "") }}'

- name: Create the clamsmtp templates directory
  file:
    path: /etc/clamsmtp
    state: directory
    owner: clamsmtp
    group: clamsmtp
    mode: '0700'

- name: Copy the virus alert templates
  template:
    src: '{{ item }}'
    dest: '/etc/clamsmtp/virus-alert-default.eml'
    owner: clamsmtp
    group: clamsmtp
    mode: '0600'
  with_first_found:
    - 'virus-alert-{{ lang }}.eml'
    - 'virus-alert-default.eml'

- name: Create the logs folder for clamsmtp
  file:
    path: /var/log/clamsmtp
    owner: clamsmtp
    group: clamsmtp
    mode: '0700'
    state: directory

- name: Copy the virus alert script
  copy:
    src: virus-alert.sh
    dest: /usr/local/bin/virus-alert.sh
    owner: clamsmtp
    group: clamsmtp
    mode: '0755'

# AppArmor configuration ======================================================
- name: Install some dovecot AppArmor profile
  when: security.app_armor
  tags: security, apparmor
  register: aa_templates
  template:
    src: 'apparmor.d/{{ aa_config }}'
    dest: '/etc/apparmor.d/{{ aa_config }}'
  with_items:
    - usr.sbin.clamsmtpd
  loop_control:
    loop_var: aa_config

- name: Activate AppArmor profiles
  when: security.app_armor and aa_templates.changed
  tags: security, apparmor
  notify: Restart AppArmor service
  command: 'aa-complain {{ aa_config }}'
  with_items:
    - usr.bin.freshclam
    - usr.sbin.clamd
  loop_control:
    loop_var: aa_config
