---

- name: Install PostgreSQL database server
  apt:
    name: "{{ pkg }}"
    state: present
  with_items:
    - postgresql-common
    - postgresql-client
    - postgresql
  loop_control:
    loop_var: pkg

