---

- name: Set ldap org base
  ansible.builtin.set_fact:
    ldap_org_base: 'dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  tags: facts

- name: Load or create the password for the read-only account
  no_log: '{{ not system.devel }}'
  ansible.builtin.set_fact:
    ldap_ro_password: '{{ lookup(creds.store, creds.prefix + "/ldap/readonly") }}'
  tags: facts

- name: Create the list of languages for fts
  ansible.builtin.set_fact:
    fts_languages: '{{ languages | map(attribute="id") }}'
  tags: facts
