---

- name: Copy the attachment on the remote server
  copy:
    src: 'check/{{ attachment.uid }}.{{ attachment.extension }}'
    dest: '/tmp/file.data'

# Check if the parser can return the string when converting to text
- name: Check if the text conversion script returns the uuid ({{ attachment.description }})
  shell: >-
    set -o pipefail ;
    cat /tmp/file.data
    | /usr/local/bin/decode2text {{ attachment.mime }}
    | grep "{{ attachment.search | default(attachment.uid) }}"
  args:
    executable: /bin/bash

- name: Delete the temporary file
  file:
    path: /tmp/file.data
    state: absent
