---
# These are the default values, you can copy and paste into your system.yml
# configuration file for customisation.

# Default network settings
# If you are behind a NAT, perhaps you will want to
# replace "auto" by your real external IP address
# The backup IP address is interesting if
# you are hosting your own DNS server.
network_default:
  external_ip: auto
  backup_ip: ~

# Standard policies
policies:
  system:
    password: 'length=16 chars=ascii_letters,digits'
    passphrase: 'length=40'

# LDAP configuration
ldap:
  hostname: 'ldap.{{ network.domain }}'
  organization:
    domain: '{{ network.domain }}'
    base: 'dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  users:
    dn: 'ou=users,dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  groups:
    dn: 'ou=groups,dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  manager:
    uid: manager
    dn: 'cn=manager account, ou=users, dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  readonly:
    uid: readonly
    dn: 'cn=readonly account, ou=users, dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  admin:
    dn: 'cn=admin,dc={{ network.domain | regex_replace("\.", ",dc=") }}'
    desc: administrator account
  postmaster:
    uid: postmaster
    dn: 'cn=postmaster account, ou=users, dc={{ network.domain | regex_replace("\.", ",dc=") }}'
    # See https://www.ietf.org/rfc/rfc2142.txt
    mailAliases:
      - 'abuse@{{ network.domain }}'
      - 'noc@{{ network.domain }}'
      - 'security@{{ network.domain }}'
      - 'mailer-daemon@{{ network.domain }}'
      - 'webmaster@{{ network.domain }}'
      - 'hostmaster@{{ network.domain }}'
      - 'admin@{{ network.domain }}'
      - 'root@{{ network.domain }}'

  # password params
  roPasswdParams: "{{ playbook_dir }}/../../backup/{{ network.domain }}/ldap/readonly.pwd {{ policies.system.password }}"
  managerPasswdParams: "{{ playbook_dir }}/../../backup/{{ network.domain }}/ldap/manager.pwd {{ policies.system.password }}"
  adminPasswdParams: "{{ playbook_dir }}/../../backup/{{ network.domain }}/ldap/admin.pwd {{ policies.system.password }}"
  postmasterPasswdParams: "{{ playbook_dir }}/../../backup/{{ network.domain }}/ldap/postmaster.pwd {{ policies.system.password }}"


# Encryption parameters
encryption:
  systemKeyParams: "{{ playbook_dir }}/../../backup/{{ network.domain }}/encryption/system-key.pwd {{ policies.system.passphrase }}"
  backupKeyParams: "{{ playbook_dir }}/../../backup/{{ network.domain }}/encryption/backup-key.pwd {{ policies.system.passphrase }}"

###############################################################################
# Email related default options
mail_default:
  max_attachment_size: 25   # In megabytes
  autoconfig: true          # Support Thunderbird automatic configuration
  autodiscover: false       # Support MS Outlook automatic configuration (uses https)
  quota:
    port: 30000             # port used by dovecot for the quota daemon
    default: 1G             # Maximum allowed mailbox size for your users.
  discard_duplicates: false # Discard duplicates messages. It is safe, but has some side
                            # effects when you are sending a message to a mailing list.
                            # This is now disabled by default.
                            # The default timerange to search duplicated messages is one hour.
  #############################################################################
  # Postfix options
  postfix:
    mynetworks: ~           # Authorized IP addresses to send emails without authentication
                            # e.g. 192.168.0.0/16, 172.16.0.0/12, 10.10.0.0/8

                            # Put anything you want here, even on multiple lines, this will
                            # be added on main.cf. See the example here:
    submission:
      port: 587
    # extra_settings: |
    #   disable_vrfy_command = no
    #   frozen_delivered_to = no

  #############################################################################
  antispam:                 # Check inbound and outbound emails for viruses
    active: true            # or false
    port: 33000             # port to use for the antivirus daemon
    webui:                  # rspamd web interface
      active: true          # Activate or not
      allow:                # a list of IP address that can access the web interface
        - 192.168.0.0/16    # RFC1918 local networks
        - 172.16.0.0/12
        - 10.0.0.0/8
  #############################################################################
  antivirus:                # Check inbound and outbound emails for viruses
    port: 34000             # port to use for the antivirus daemon
    active: true            # or false
    action: drop            # Action to do when a virus is found in an email: bounce or drop
                            # be careful, bouncing external emails is a way to expose clamav
                            # usage
    quarantine: yes         # Place emails with a virus in quarantine, for further analysis
    use_proxy: false        # use tor / privoxy to dowload updates
  #############################################################################
  impersonate:              # Activate dovecot "master" user feature, ideal for families and
                            # communities
    active: false           # https://wiki2.dovecot.org/Authentication/MasterUsers
    master: master          # master user name
    separator: '*'          # Separation char between master user / real user name.
  #############################################################################
  import:                   # If you have users with "import" email active scripts,
                            # set this flag to true
    username: import        # The name of the user that import emails
    active: false           # A master user, with reduced rights will be created, to append
                            # imported emails
                            # in user's mailboxes.
  #############################################################################
  # Dovecot / solr FTS (Full Text search)
  fts:
    active: true
    langs:
      - id: fr
        name: French
      - id: en
        name: English
  #############################################################################
  # Virtual folders
  virtual_folders:          # Create virtual IMAP folders, like flagged,
    active: true            # deleted, unread, conversations, etc.
    all_limit: 3650         # The maximum number of days to include the the Search/All folder.
                            # It is useful to put a limit here if you have a lot of messages
                            # and limited hardware resources
  #############################################################################
  recipient_delimiter: '+'  # The character you want to use to split email address
                            # from mailbox, i.e.:
                            # when receiving a message to john+lists@example.com,
                            # it should go directly to the 'lists' folder.
                            # It is also useful to track which sites are selling or sharing your
                            # email address to other sites.
  #############################################################################
  # Sieve specific parameters
  # set debug to true to create log files in the user's mail/sieve/logs.
  # useful to debug sieve without setting the debug flag system wide
  sieve:
    debug: true
  #############################################################################
  # Log access times and IP addresses in the users directory
  log_access:
    active: false

###############################################################################
# Default password policies for users
passwords_default:
  min_length: 8
  max_age: 31536000        # 365 days max
  max_failure: 5
  expire_warning: 259200   # 3 days
  require_nonalpha: true
  # Keep track of the passwords you have used before
  # If you do not want, set this value to 0
  # Passwords are stored using salted SHA512, safe enough
  remember: 12
  # Password quality module
  quality:
    enforce: true
    params:
      - name: retry
        value: 5
      - name: minlen
        value: 8
      - name: minclass
        value: 3
      - name: maxrepeat
        value: 3
      - name: maxclassrepeat
        value: 4
      - name: lcredit
        value: 1
      - name: ucredit
        value: 1
      - name: ocredit
        value: 3
      - name: dcredit
        value: 1
      - name: difok
        value: 3

###############################################################################
# Default system settings
system_default:
  release: stretch
  login: true
  devel: false
  debug: false
  reboot_timeout: 180

###############################################################################
# Once the system is in place, it is possible to use 'limit' for the rule,
# instead of allow. It is also possible to use fail2ban, which is installed anyway
# You can have as many sources as you want, with a comment to easily keep track
# of your rules
firewall_default:
  fwknop:
    install: false
    port: random
  ssh:
    - src: any
      rule: allow
      comment: allow SSH from anywhere
  output:
    policy: deny
    rules:
      - dest: any
        port: 80,443
        comment: 'Allow web access'
      - dest: any
        proto: udp
        port: 53
        comment: 'Allow DNS requests'
      - dest: any
        proto: udp
        port: 123
        comment: 'Allow NTP requests'
      - dest: any
        proto: udp
        from_port: 68
        port: 67
        comment: 'Allow DHCP requests'
      - dest: any
        port: 25
        comment: 'Allow SMTP connections to other servers'
      - dest: any
        port: 110,995,143,993
        comment: 'Allow the recuperation of emails on other servers (POP/IMAP)'

###############################################################################
# Extra security values
security_default:
  auto_update: true
  app_armor: true
  ssh_disable_root_access_with_password: true
  lock_root_password: true
  alerts_email:
    - 'admin@{{ network.domain }}'
  # various options when luks is installed
  luks:
    yubikey: false

###############################################################################
# Dictionaries to install in the system
dictionaries_default:
  - name: English
    id: en

###############################################################################
# Install a static web site on www.yourdomain.com
# Still requests two certificates:
# One for for https://yourdomain.com/ and one for https://www.yourdomain.com
website_default:
  install: false

###############################################################################
# Install a static web site on www.yourdomain.com using Hugo (https://gohugo.io/)
# Still requests two certificates:
# One for for https://yourdomain.com/ and one for https://www.yourdomain.com
# Place your site in the backup folder: backup/<network.domain>/website-hugo/
# It will be served by the internal Hugo server.
# Example of a configuration here

hugo_default:
  install: false
  site_title: "Site title"
  theme:
    name: hugo-tranquilpeak-theme

###############################################################################
# Install a webmail, or not...
webmail_default:
  install: true
  type: roundcube

###############################################################################
# Act as a backup server using borgbackup (https://www.borgbackup.org/)
backup_default:
  install: false

###############################################################################
# Default list of development packages to install
# You can override it in your config/system.yml file
# they are installed when running the playbook dev-support,
# and removed when using dev-cleanup

devel_default:
  packages:
    - mc
    - telnet
    - dnsutils
    - whois
    - tmux
    - pfqueue
    - aptitude
    - man
    - less
    - vim
    - net-tools
    - file
    - swaks
    - curl
    - locate
    - colorized-logs
    - bash-completion
    - cyrus-clients
    - zsh
  root:
    shell: /bin/zsh


###############################################################################
# DKIM keys default parameters
dkim_default:
  key_size: 4096
  selector: main
  note: 'main DKIM key for the domain {{ network.domain }}'
  milter:
    port: 31000

###############################################################################
# DMARC keys default parameters
dmarc_default:
  domain:
    # none, quarantine or reject
    policy: quarantine
  subdomain:
    # none, quarantine or reject
    policy: quarantine
  rua:
    email: 'postmaster@{{ network.domain }}'
    max_size: 10240
  ruf:
    email: 'postmaster@{{ network.domain }}'
    max_size: 10240
  reporting:
    format: afrf    # or iodef
    interval: 86400
    percent: 100
    # The following parameters are for reports sending
    # Not activated yet until fully tested on a live system
    sending: false
    organisation: 'rspamd / homebox'
  dkim_align: strict
  spf_align: relaxed
  send_reports:
    active: false
  milter:
    port: 32000

###############################################################################
# Jabber server
# The port numbers are not exposed externally, everything
# is behind nginx, in https.
# By default, the server is open to other servers (public flag to true).
# To restrict to only a few domains, set the flag to false, and
# enter the list of domains in the trust array
ejabberd_default:
  install: true
  allow_contrib_modules: false
  # Ban clients after too much authentication failures (1h after 10 attempts)
  fail2ban:
    active: true
    lifetime: 3600
    failures: 10
  # Server-to-server communication
  s2s:
    active: true
    use_starttls: required_trusted
    public: true
    trust:
      - jabber.org
  # https upload module
  http_upload:
    port: 5443
    secret_length: 40
    max_size: 104857600
    thumbnail: false
  # direct file transfer
  file_transfer:
    port: 7778
  # traffic shaper
  shaper:
    normal: 1000
    fast: 50000
    proxyrate: 10240 # file transfer proxy

###############################################################################
# Gandi automatic DNS update
# This is now obsolete, as Homebox come with its own DNS server
# However, we could keep this for Glue records management
# Your Gandi Key should be 24 characters long, e.g. zaNGbUVIvi1KbYb6PPMdiQLh
# update: Automatic update of your DNS server
# test: test mode: does not activate the DNS zone straight
# add_wildcard:  Create a wildcard entry to redirect all traffic to your box
dns_default:
  update: false
  test: true
  add_wildcard: true
  gandi:
    handle: JD123-GANDI
    key: zaNGbUVIvi1KbYb6PPMdiQLh

###############################################################################
# Bind server defaults
bind_default:
  # Bind is actually in testing phase, feedback welcome
  install: false
  # Default servers to forward queries
  forward:
    - 8.8.8.8
    - 8.8.4.4
    - 1.1.1.1
  # Timing configuration (see https://www.ripe.net/publications/docs/ripe-203)
  refresh: 86400          # 24 hours
  retry: 7200             # 2 hours
  expire: 3600000         # 10000 hours
  neg_cache_ttl: 172800   # 2 days
  ttl: 3600               # 1 hour
  # General MX configuration
  mx_priority: 10
  # List of backup MX records, if the server is unreachable
  # The default is an empty list
  mx_backup: []
  # Example of records
  # mx_backup:
  #   - fqdn: spool.mail.gandi.net
  #     priority: 10
  #   - fqdn: fb.mail.gandi.net
  #     priority: 50
  # List of trusted servers to accept cache / recursive queries
  trusted:
    - src: 192.168.0.0/16
      comment: LAN
    - src: localhost
    - src: localnets
      comment: Local networks
  #  - src: 72.13.58.64
  #    comment: https://dnssec-analyzer.verisignlabs.com
  # DNSSEC options
  dnssec:
    active: false
    algo: RSASHA256

###############################################################################
# Gogs installation with LDAP authentication
# Beta feature, work in progress
# The super administrator is "postmaster" for now.
gogs_default:
  install: false
  public: false         # not open to public by default
  allow:                # a list of IP address that can access the web interface
    - 192.168.0.0/16    # RFC1918 local networks
    - 172.16.0.0/12
    - 10.0.0.0/8


###############################################################################
# Transmission bittorrent client installation
transmission_default:
  install: false
  public: false         # not open to public by default, only to local networks
  allow:                # a list of IP address that can access the web interface
    - 192.168.0.0/16    # RFC1918 local networks
    - 172.16.0.0/12
    - 10.0.0.0/8
  # Block list
  # example: http://john.bitsurge.net/public/biglist.p2p.gz
  blocklist_url: ~
  # Protocol options
  pex: true
  dht: true
  port_forwarding: false
  # Encryption parameters
  # 0 = unencrypted, 1 = prefer encrypted, 2 = require encrypted
  encryption: 2
  # Directories
  download_dir: /var/lib/transmission-daemon/downloads
  incomplete_dir: /var/lib/transmission-daemon/incomplete
  # Download parameters
  speed_limit_down: 0
  download_limit: 100
  download_queue: 5
  download_theme: light    # or dark
  # Upload limits
  speed_limit_up: 0
  upload_limit: 100
  seed_queue_size: 5

# Default posix groups
posix_groups_default:
- gid: mail_users
  description: Mail users
  gidNumber: 1001
  mail: 'users@{{ network.domain }}'
- gid: administrators
  description: Administrators
  gidNumber: 2000
  mail: 'admin@{{ network.domain }}'

# The onion router
tor_default:
  install: false
  port: 9050
  accept_from:
    - 127.0.0.1

# Privoxy privacy proxy
privoxy_default:
  install: false
  tor_forward: false
  port: 8118
  accept_from:
    - 10.0.0.0/8
    - 192.168.0.0/16
    - 172.16.0.0/20
  # Automatically add and update rules using adblockplus community rules
  adblock_rules:
    install: true
    list:
      - https://easylist.to/easylist/easylist.txt
      - https://easylist.to/easylist/easyprivacy.txt
      - https://easylist.to/easylist/fanboy-annoyance.txt
      - https://easylist.to/easylist/fanboy-social.txt
  # Custom options for privoxy
  custom_settings: |
    # Put anything you want here,
    # even on multiple lines

# Zabbix monitoring
zabbix_default:
  install: false
  guest_account: false  # Allow guest account or not
  public: false         # not open to public by default
  allow:                # a list of IP address that can access the web interface
    - 192.168.0.0/16    # RFC1918 local networks
    - 172.16.0.0/12
    - 10.0.0.0/8

# Default settings for SOGo groupware
sogo_default:
  install: true
  appointment_send_emails: true
  vacation: true
  forward: true
  sieve_scripts: true
  first_day_of_week: 1 # 1 is Monday
  day_start_time: 9
  day_end_time: 17
  time_format: '%H:%M'
  refresh_view_check: every_minute
  auxiliary_accounts: true
  # Possible values: https://sogo.nu/files/docs/SOGoInstallationGuide.html#_general_preferences
  language: English
  enable_public_access: false
  password_change: true
