# HomeBox configuration example.
# Copy this file into config.yml, and edit it with the values that suits you
# For a more comprehensive list of settings, you can see the default file in
#

###############################################################################
# Domain and hostname information
network:
  domain: example.com
  hostname: mail.example.com

###############################################################################
# Users
# List of users to create in the system
users:
- uid: john
  cn: John Doe
  first_name: John
  last_name: Doe
  mail: john.doe@example.com
  password: 'xIlm*uu7'
  aliases:
    - john@homebox.space
  external_accounts:
    - name: outlook
      type: live.com
      user: john.doe@live.co.uk
      password: ebsipmfwuqsopxsg
      get_junk: true
      get_trash: true
  # Allow access to backup
  backup_ssh_key:
    type: ssh-rsa
    comment: jdoe-backup-key
    data: >-
      AAAAB3NzaC1yc2EAAAADAQOSPAABAQDLQ/Odv+oOWbNdaBwegtwBryh/NsRkM6NNRd30kgoza39+
      TtOIXNcLsnProh6ynJxNBdxxx6wa6/dkA/3opbdprovU676WfWEFOpjNzABGtrgU6uIzihc51nm49/
      SsP7rNLXfh0ZfQlCjhR6oL+oe3ggnnrPwtEpsZSDjR8Qx4gYCxZ+2H4C5QcvotZ6i/9pc7uv9Gh2Rd
      iDAoQDIeedZFygruhpFK5VEQnXf2KB8z4MCT1Nwk5/7VUE1xTB0AHoUBMLF4RMmkPrfhfPfGbXL97e
      BaxeEVdIurdEoYi7EPc3ZT/NI2Rh136mMZLUb7QupinA0yfTc1FEhkDCvE9L/5
- uid: jane
  cn: Jane Doe
  first_name: Jane
  last_name: Doe
  mail: jane.doe@example.com
  password: 'Tlwril!8'
  aliases:
    - jane@homebox.space
  external_accounts:
    - name: work
      type: imap
      host: imap.company.com
      user: jane
      password: '0lih*(&nTrom'
      max_messages: 10
    - name: gmail
      type: gmail
      user: jane.doe@gmail.com
      password: yjkytvofwbqlcmry
      get_important: false
      get_junk: true
      get_trash: true
      max_messages: 10
    - name: yahoo
      type: ymail
      user: jane.doe@ymail.com
      password: zakxizvqpkxzibnn
      get_junk: true
      get_trash: true
      max_messages: 10

###############################################################################
# Email related default options
# mail:
#   max_attachment_size: 25   # In megabytes
#   autoconfig: true          # Support Thunderbird automatic configuration
#   autodiscover: false       # Support MS Outlook automatic configuration (uses https)
#   quota:
#     default: 1G             # Maximum allowed mailbox size for your users.
#                             # The safe maximum value will be automatically computed in a next version.
#   discard_duplicates: true  # Discard duplicates messages. It is safe, but you can disable if you are worried
#                             # The default timerange is 1h
#   #############################################################################
#   antivirus:                # Check inbound and outbound emails for viruses
#     active: true            # or false
#     action: drop            # Action to do when a virus is found in an email: bounce or drop
#                             # be careful, bouncing external emails is a way to expose clamav usage
#     send_warnings: false    # Send a warning email to - internal - users who are sending viruses
#     quarantine: yes         # Place emails with a virus in quarantine, for further analysis
#   #############################################################################
#   impersonate:              # Activate dovecot "master" user feature, ideal for families and communities
#     active: false           # https://wiki2.dovecot.org/Authentication/MasterUsers
#     master: master          # master user name
#     separator: '*'          # Separation char between master user / real user name.
#   #############################################################################
#   import:                   # If you have users with "import" email active scripts, set this flag to true
#     username: import        # The name of the user that import emails
#     active: false           # A master user, with reduced rights will be created, to append miported emails
#                             # in user's mailboxes.
#   #############################################################################
#   # Dovecot / solr FTS (Full Text search)
#   fts:
#     active: true
#     langs:
#       - id: fr
#         name: French
#       - id: en
#         name: English
#   #############################################################################
#   advanced_features: false  # Use some advanced features that will need the latest version of dovecot
#                             # from stretch-backports, like those below.
#                             # like sending emails to an international addresses (e.g. andr√©@homebox.space)
#   recipient_delimiter: '+'  # The characters you want to use to split email address from mailbox, i.e.:
#                             # when receiving a message to john+lists@example.com, it should go directly to
#                             # the 'lists' folder...

###############################################################################
# System related
# system:
#   devel: true
#   debug: true

###############################################################################
# Gandi automatic DNS update
# Your Gandi Key should be 24 characters long, e.g. zaNGbUVIvi1KbYb6PPMdiQLh
# dns:
#   update: false         # Automatic update of your DNS server
#   test: true            # test mode: does not activate the DNS zone straight
#   add_wildcard: false   # Create a wildcard entry to redirect all traffic to your box
#   gandi:
#     handle: JD123-GANDI
#     key: zaNGbUVIvi1KbYb6PPMdiQLh

###############################################################################
# Once the system is in place, it is possible to use 'limit' for the rule, instead of any.
# It is also possible to use fail2ban, which is installed anyway
# firewall:
#   ssh:
#     from: any
#     rule: allow

###############################################################################
# Install a webmail, or not...
# webmail:
#   install: true
#   type: roundcube

###############################################################################
# Extra security values
# security:
#   auto_update: true
#   app_armor: true

###############################################################################
# Backup configuration
# You can have multiple backup configuration:
# remote (ssh or samba) and local directory
# All backups will be encrypted
# Compression: See borg documentation

# backup:
#   install: true
#   type: borgbackup
#   locations:

# Exemple 1: backup on the local disk. Useful for small backup only
#   - name: local
#     url: dir://var/backups/homebox
#     active: yes                      # The backup is currently active
#     frequency: daily                 # Run the backup every day
#     keep_daily: 3                    # Keep the last three days locally
#     compression: lz4                 # Compression scheme to use (lz4 by default)

# Example 2: Backup on a remote location, over SSH
#   - name: router
#     url: ssh://fw.office.pm:/home/backup/homebox
#     active: yes                      # The backup is currently active
#     frequency: daily                 # Run the backup every day
#     keep_daily: 7                    # Keep the last seven days (default value)
#     keep_weekly: 4                   # Keep the last four weeks (default value)
#     keep_monthly: 6                  # Keep the last six months (12 by default)
#     compression: lz4                 # Compression scheme to use (lz4 by default)

# Example 3: Backup on a network NAS mounted via Samba / CIFS
#   - name: nas
#     url: smb://backup:giuwh97kwerr@ftp.office.pm:/home/backup/homebox
#     active: yes                      # The backup is currently active
#     frequency: weekly                # Run the backup every week
#     keep_weekly: 4                   # Keep the last four weeks (default value)
#     keep_monthly: 6                  # Keep the last six months (12 by default)
#     compression: zlib,6              # Compression scheme to use (lz4 by default)

# Exemple 4: Backup on a USB stick labelled as "backup", when inserted or periodically
#   - name: usb-backup
#     url: usb://media/backup/
#     active: yes                      # The backup is currently active
#     frequency: weekly                # Run the backup every week
#     keep_weekly: 4                   # Keep the last four weeks (default value)
#     keep_monthly: 6                  # Keep the last six months (12 by default)
#     compression: zlib,6              # Compression scheme to use (lz4 by default)


###############################################################################
# Dictionaries to install in the system, will be displayed in roundcube for now.
# dictionaries:
#   - name: English
#     id: en
#   - name: French
#     id: fr
#   - name: Spanish
#     id: es
