---

# Install and configure certificate for postfix
- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/../../config/defaults.yml'
  vars:
    certificate:
      type: smtp
  roles:
    - certificates
