# Create the accounts
# If you set the optino -e clean_users=true then
# the script will drop the users from the database first
# Do not delete the previous users if running again the script

- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/defaults/main.yml'
    - '{{ playbook_dir }}/roles/ldap/variables/main.yml'
  vars:
    clean_users: '{{ clean | default(false)}}'
    clean_groups: '{{ clean | default(false)}}'
    certificate:
      type: ldap
  roles:
    - certificates
    - ldap
