---

# Create the accounts
# If you set the optino -e clean_users=true then
# the script will drop the users from the database first
# Do not delete the previous users if running again the script

- hosts: homebox
  vars:
    certificate:
      type: ldap
  roles:
    - role: certificates
      tags: certificates
    - ldap
