---

# Install rspamd web interface
- hosts: homebox
  vars:
    redirect: true
    certificate:
      type: rspamd
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/../../config/defaults.yml'
  roles:
    - certificates
    - rspamd-web
