---

# Prepare the system
- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/../../config/defaults.yml'
  roles:
    - packages
    - system-prepare
