---

# Web site configuration ======================================================

- name: Remove nginx configuration
  tags: nginx
  notify:
    - Check nginx config
    - Restart nginx
  file:
    path: '{{ path }}'
    state: absent
  with_items:
    - '/etc/nginx/sites-available/transmission.{{ network.domain }}.conf'
    - '/etc/nginx/sites-enabled/transmission.{{ network.domain }}.conf'
  loop_control:
    loop_var: path

# Uninstall daemon ============================================================

- name: Uninstall the transmission package
  tags: apt
  apt:
    purge: true
    name: transmission-daemon
    state: absent

# System configuration ========================================================
- name: Remove the network system limits for transmission
  tags: sysctl
  sysctl:
    name: '{{ sysctl.name }}'
    value: '{{ sysctl.value }}'
    state: absent
  with_items:
    - name: net.core.rmem_max
      value: 4194304
    - name: net.core.wmem_max
      value: 4194304
  loop_control:
    loop_var: sysctl

# Transmission folder archive =================================================
- name: Archive transmission folder
  shell: >-
    mv /var/lib/transmission-daemon /var/backups/transmission-daemon
  args:
    warn: false
    creates: /var/backups/transmission-daemon

- name: Archive transmission folder
  file:
    path: /var/lib/transmission-daemon
    state: absent

# Users cleanup ===============================================================
- name: Remove transmission user
  user:
    name: debian-transmission
    state: absent

# Remove firewall rules =======================================================
- name: Clean up firewall rules
  shell: >-
    ufw status numbered
    | grep transmission
    | sed -r 's/^\[(..)\] .*/echo y | ufw delete \1/'
    | sort -r | sh
  args:
    warn: no
    
# AppArmor configuration ======================================================

- name: Remove nginx and transmission AppArmor profiles
  when: security.app_armor
  tags: security, apparmor
  register: aa_config
  notify:
    - Check nginx config
    - Restart nginx
  file:
    path: '/etc/apparmor.d/{{ file }}'
    state: absent
  with_items:
    - local/transmission-web
    - usr.bin.transmission-daemon
  loop_control:
    loop_var: file

- name: Add transmission AppAromor specific configuration
  when: security.app_armor
  tags: security, apparmor
  lineinfile:
    path: /etc/apparmor.d/usr.sbin.nginx
    line: '  #include <local/transmission-web>'
    state: absent

- name: Activate AppArmor profiles
  when: security.app_armor and aa_config.changed
  tags: security, apparmor
  command: 'aa-enforce usr.sbin.nginx'
  notify: Restart AppArmor service
