---

- name: Load or create the password for the admin user
  no_log: '{{ not system.devel }}'
  ansible.builtin.set_fact:
    admin_password: >-
      {{ lookup(creds.store, network.domain + "/user/admin"
      + creds.opts.create) }}

- name: Use a random uid and gid numbers
  ansible.builtin.set_fact:
    uid_number: '{{ 2000 + (999 | random) }}'
    gid_number: '{{ 2000 + (999 | random) }}'

- name: Create Administrators group
  ansible.builtin.group:
    name: '{{ system.admin.group_name | lower }}'
    gid: '{{ gid_number | int }}'

- name: Create the Administration user
  ansible.builtin.user:
    name: '{{ system.admin.name }}'
    group: '{{ system.admin.group_name }}'
    groups: sudo
    password: '{{ admin_password | password_hash("sha512") }}'
    uid: '{{ uid_number | int }}'
