---

- name: Remove Development support packages
  tags: development
  apt:
    name: '{{ pkg }}'
    state: absent
  with_items:
    - '{{ devel.packages }}'
  loop_control:
    loop_var: pkg

- name: Install a correct bashrc for root
  when: system.devel
  tags: development
  file:
    path: '/root/.{{ dot_file }}'
    state: absent
  with_items:
    - bashrc
    - zshrc
    - vimrc
  loop_control:
    loop_var: dot_file

- name: Restore the default bashrc
  when: system.devel
  tags: development
  copy:
    remote_src: yes
    src: '/etc/skel/.bashrc'
    dest: '/root/.bashrc'

- name: Set the default shell for the root user
  when: system.devel
  tags: development
  user:
    name: root
    shell: /bin/dash
  
