---

- name: Load postmaster XMPP password
  no_log: '{{ not system.devel }}'
  ansible.builtin.set_fact:
    postmaster_password: >-
      {{ lookup(creds.store, network.domain + "/ldap/postmaster") }}
  tags: xmpp

- name: Push the xmpp parameters
  notify: Restart Prometheus XMPP alerts
  ansible.builtin.template:
    src: xmpp-alerts.yml
    dest: /etc/prometheus/xmpp-alerts.yml
    mode: 0600
  tags: xmpp

- name: Allow prometheus to read this configuration file
  notify: Restart Prometheus XMPP alerts
  ansible.posix.acl:
    path: /etc/prometheus/xmpp-alerts.yml
    entity: prometheus
    etype: user
    permission: r
    state: present
  tags: xmpp
