# Postfix blacklists to use
# See https://en.wikipedia.org/wiki/Comparison_of_DNS_blacklists
dns_blacklists:
  - zen.spamhaus.org
  - b.barracudacentral.org

antispam:
  milter:
    name: rspamd
    port: '{{ milter_antispam_port }}'

master_addresses:
  - postmaster
  - mailer-daemon
  - postmaster
  - hostmaster
  - webmaster
  - abuse
  - masteruser
  - admin
  - root
