---

- name: Install opendmarc AppArmor profile
  template:
    src: apparmor.conf
    dest: /etc/apparmor.d/usr.sbin.opendmarc
    force: no

- name: Activate AppArmor profiles
  command: 'aa-enforce usr.sbin.opendmarc'
  notify: Restart AppArmor service
