---

- name: Install opendmarc related packages
  tags: apt
  apt:
    name: opendmarc
    state: latest

- name: Comment all active socket for DMARC
  tags: config
  notify: Restart OpenDMARC service
  replace:
    path: /etc/default/opendmarc
    regexp: '^SOCKET=(.*)'
    replace: '#SOCKET=\1'

- name: Comment all active socket for DMARC
  tags: config
  notify: Restart OpenDMARC service
  replace:
    path: /etc/opendmarc.conf
    regexp: '^Socket(.*)'
    replace: '# Socket=\1'

- name: Add tcp interface on localhost
  notify: Restart OpenDMARC service
  tags: config
  lineinfile:
    path: /etc/opendmarc.conf
    line: '{{ line }}'
  with_items:
    - 'Socket inet:{{ dmarc.milter.port }}@localhost'
    - 'AutoRestart 1'
  loop_control:
    loop_var: line

# name server config ==========================================================

- name: Generate DMARC record from settings
  tags: bind
  when: bind.install
  template:
    src: 20-dmarc.bind
    dest: /etc/homebox/dns-entries.d/20-dmarc.bind

# AppArmor configuration ======================================================

- name: Install opendmarc AppArmor profile
  when: security.app_armor
  tags: security, apparmor
  template:
    src: 'apparmor.d/usr.sbin.opendmarc.cf'
    dest: '/etc/apparmor.d/usr.sbin.opendmarc'
    force: no

- name: Activate AppArmor profiles
  when: security.app_armor
  tags: security, apparmor
  command: 'aa-enforce usr.sbin.opendmarc'
  notify: Restart AppArmor service

