---

- name: Install opendmarc related packages
  tags: opendmarc
  apt:
    name: '{{ pkg }}'
    state: latest
  with_items:
    - opendmarc
  loop_control:
    loop_var: pkg

- name: Comment all active socket for DMARC
  tags: opendmarc
  notify: Restart OpenDMARC service
  replace:
    path: /etc/default/opendmarc
    regexp: '^SOCKET=(.*)'
    replace: '#SOCKET=\1'

- name: Comment all active socket for DMARC
  tags: opendmarc
  notify: Restart OpenDMARC service
  replace:
    path: /etc/opendmarc.conf
    regexp: '^Socket(.*)'
    replace: '# Socket=\1'

- name: Add tcp interface on localhost
  notify: Restart OpenDMARC service
  tags: opendmarc
  lineinfile:
    path: /etc/opendmarc.conf
    line: 'Socket inet:{{ dmarc.milter.port }}@localhost'


