---

###############################################################################
users_defaults:
  uid_start: 1001
  gid_start: 1001
  shell: /bin/dash


packages:
  install:
    - acl
    - slapd
    - python-ldap
    - python-passlib
    - ldapscripts
    - libpam-pwquality
    - ldapvi
    - unscd
  remove:
    - libpam-cracklib
    - nscd

indexed_fields:
  - uid
  - cn
  - sn
  - givenName
  - mail
  - memberUid
  - uidNumber
  - gidNumber
  - intlMailAddr
  - displayName
  - telephoneNumber
