---

# The certbot package need to be installed
- name: Create the certificate
  tags: cert
  command: >-
    /usr/bin/certbot certonly
    --non-interactive
    --webroot
    {{ system.devel | ternary("--break-my-certs", "") }}
    --webroot-path "{{ site_root }}"
    --domain "{{ certificate_fqdn }}"
    {{ "-d " + domain_alias + "." + network.domain if domain_alias is defined and (domain_alias | length > 0) else "" }}
    --email "admin@{{ network.domain }}"
    {{ domain_alias_cmd is defined | ternary("--expand", "") }}
    {{ "" if not system.devel
          else "--test-cert" if devel.acme_server == 'staging'
          else "--no-verify-ssl --server https://10.30.50.2:14000/dir --force-renewal --renew-with-new-domains" }}
    --agree-tos

- name: Copy the original certificate renewal script from certbot package
  template:
    src: cron-certbot
    dest: /etc/cron.d/certbot
    force: no

- name: Use webroot to upgrade the certificates
  tags: upgrade
  register: renewal_config
  replace:
    path: '/etc/letsencrypt/renewal/{{ certificate_fqdn }}.conf'
    regexp: authenticator = standalone
    replace: authenticator = webroot
