---

- name: Install packages to send alerts using xmpp
  when: ejabberd.install
  tags: apt
  apt:
    name: sendxmpp
    state: present

- name: Deploy the global configuration file for access check settings
  tags: config
  template:
    src: access-check.cf
    dest: /etc/homebox/access-check.conf
    mode: 644

- name: Create the security directory for each user
  file:
    path: '/home/users/{{ user.uid }}/security'
    owner: '{{ user.uid }}'
    group: users
    state: directory
    mode: 0700
  with_items:
    - '{{ users }}'
    - uid: postmaster
  loop_control:
    loop_var: user

- name: Copy the configuration file in each user directory
  template:
    src: access-check-user.cf
    dest: '/home/users/{{ user.uid }}/.config/homebox/access-check.conf'
    owner: '{{ user.uid }}'
    group: users
    force: no
  with_items:
    - '{{ users }}'
    - uid: postmaster
  loop_control:
    loop_var: user

- name: Initialise the postmaster user password parameters
  when: ejabberd.install
  set_fact:
    postmaster_password_params: "{{ backup_directory }}/ldap/postmaster.pwd {{ policies.system.password }}"

- name: Create the master user account password
  when: ejabberd.install
  no_log: true
  set_fact:
    postmaster_password: '{{ lookup("password", postmaster_password_params) }}'

- name: Create the configuration to send xmpp alerts using the local server
  when: ejabberd.install
  template:
    src: postmaster-sendxmpp.rc
    dest: /home/users/postmaster/.sendxmpprc
    mode: '0400'
    owner: postmaster
    force: no
