---

## Call the backup tasks on one or more role

# export the role you want to run in the ‘ROLE’ environment variable
# and run the playbook.

- name: Load the roles to run
  hosts: homebox
  tags: always
  tasks:
    - name: Load the roles to run
      set_fact:
        roles_list: '{{ lookup("env", "ROLE").split(",") }}'

- name: Run the backup tasls on the roles selected
  hosts: homebox
  vars:
    debug: '{{ system.debug }}'
    backup_directory: '{{ playbook_dir }}/../backup/{{ network.domain }}/'
  vars_files:
    - '{{ playbook_dir }}/../config/defaults/common-security.yml'
    - '{{ playbook_dir }}/../config/defaults/version-{{ version | default("small") }}.yml'
    - '{{ playbook_dir }}/../config/system.yml'
  tasks:
    - name: Load common settings
      tags: always
      include_role:
        name: common-init
    - name: Run the roles selected
      tags: always
      include_role:
        name: '{{ role }}'
        tasks_from: backup/main.yml
      loop: '{{ roles_list }}'
      loop_control:
        loop_var: role
