---

- name: Install hugo packages
  apt:
    name: hugo
    state: latest

- name: Create a directory for web site backup if it does not exists
  tags: backup
  delegate_to: localhost
  file:
    path: '{{ playbook_dir }}/../../backup/{{ network.domain }}/website-hugo/'
    state: directory

# Push the site if already backup up
- name: If the web site has been generated before, copy the files on the remote server
  tags: sync
  notify:
    - Check nginx config
    - Restart nginx
  synchronize:
    src: '{{ playbook_dir }}/../../backup/{{ network.domain }}/website-hugo/'
    dest: /var/www/hugo
    owner: no
    group: no
    perms: yes
    rsync_opts:
      - '--no-motd'
      - '--update'
      - '--exclude=.git*'

- name: Create the web site content with Hugo
  file:
    path: /var/www/hugo/
    state: directory

- name: Create the web site content with Hugo
  shell: hugo new site default
  args:
    chdir: /var/www/hugo/
    creates: /var/www/hugo/default/

- name: Get the site language
  set_fact:
    lang: '{{ lookup("env", "LANG") | regex_replace("\..*") }}'

- name: Create the configuration if it does not already exists
  template:
    src: config.toml
    dest: /var/www/hugo/default/config.toml
    force: no

- name: Create the web site
  tags: nginx
  notify:
    - Check nginx config
    - Restart nginx
  template:
    src: nginx.conf
    dest: '/etc/nginx/sites-available/www.{{ network.domain }}.conf'
    owner: root
    group: root
    mode: 0644

- name: Activate the site
  tags: nginx
  notify:
    - Check nginx config
    - Restart nginx
  file:
    src: '/etc/nginx/sites-available/www.{{ network.domain }}.conf'
    dest: '/etc/nginx/sites-enabled/www.{{ network.domain }}.conf'
    state: link

- name: Deactivate the website-simple site
  tags: nginx
  notify:
    - Check nginx config
    - Restart nginx
  file:
    path: /etc/nginx/sites-enabled/website-simple.conf
    state: absent

- name: Create the systemd service for Hugo
  notify:
    - Reload systemd
    - Restart hugo service
  vars:
    options:
      - '--bind="127.0.0.1"'
      - '--baseURL="https://www.{{ network.domain }}/"'
      - '--port=1313'
      - '--theme={{ hugo.theme.name }}'
      - '--appendPort=false'
  template:
    src: hugo-server.service
    dest: /etc/systemd/system/hugo-server.service

# AppArmor configuration ======================================================

- name: Install nginx AppArmor profile
  when: security.app_armor
  tags: hugo, security, apparmor
  template:
    src: apparmor.d/local/hugo-web.cf
    dest: /etc/apparmor.d/local/nginx-hugo-web

- name: Check if AppArmor nginx configuration already contains the line
  register: line_found
  shell: >-
    grep -c 'include <local/nginx-sogo>'
    /etc/apparmor.d/usr.sbin.nginx
  changed_when: false
  failed_when: false

- name: Add hugo AppAromor specific configuration
  when: security.app_armor and line_found.stdout == '0'
  register: aa_config
  tags: hugo, security, apparmor
  lineinfile:
    path: /etc/apparmor.d/usr.sbin.nginx
    line: '  #include <local/nginx-hugo-web>'
    insertbefore: '# End of local includes for homebox'

- name: Install Hugo AppArmor profile
  when: security.app_armor
  tags: hugo, security, apparmor
  template:
    src: apparmor.d/usr.bin.hugo
    dest: /etc/apparmor.d/usr.bin.hugo

- name: Activate AppArmor profiles
  when: security.app_armor and aa_config.changed
  tags: hugo, security, apparmor
  command: 'aa-enforce usr.sbin.nginx'
  notify: Restart AppArmor service

# Backup the site locally
- name: Backup the site on your local machine
  tags: sync
  synchronize:
    mode: pull
    src: /var/www/hugo/*
    dest: '{{ playbook_dir }}/../../backup/{{ network.domain }}/website-hugo/'
    perms: yes
    archive: false
    recursive: true
    rsync_opts:
      - '--no-motd'
      - '--update'
      - '--exclude=*demo*'
