---
# This role load all the default values, and merge them with user specified values.
# This is a first version, roughly copy and paste, but will evolve to something more
# elaborated later. The final purpose is fulfilled:
# Users can specify copy partial branches of default values, and not worry
# about new version changes.


################################################################################
# Merge user options with default options
- name: Combine default and user defined network settings
  run_once: true
  when: network is defined
  tags: defaults
  set_fact:
    network: '{{ network_default | combine(network, recursive=True) }}'

- name: Use default network settings
  run_once: true
  when: network is not defined
  tags: defaults
  set_fact:
    network: '{{ network_default }}'

- name: Display merged network settings
  run_once: true
  when: verbose is defined and verbose == True
  tags: defaults
  debug:
    var: network

################################################################################
# Merge user options with default options
- name: Combine default and user defined mail settings
  run_once: true
  when: mail is defined
  tags: defaults
  set_fact:
    mail: '{{ mail_default | combine(mail, recursive=True) }}'

- name: Use default mail settings
  run_once: true
  when: mail is not defined
  tags: defaults
  set_fact:
    mail: '{{ mail_default }}'

- name: Display merged mail settings
  run_once: true
  when: verbose is defined and verbose == True
  tags: defaults
  debug:
    var: mail

################################################################################
# Merge user options with default options
- name: Combine default and user defined password settings
  run_once: true
  when: passwords is defined
  tags: defaults
  set_fact:
    passwords: '{{ passwords_default | combine(passwords, recursive=True) }}'

- name: Use default passwords settings
  run_once: true
  when: passwords is not defined
  tags: defaults
  set_fact:
    passwords: '{{ passwords_default }}'

- name: Display merged password settings
  run_once: true
  when: verbose is defined and verbose == True
  tags: defaults
  debug:
    var: passwords

################################################################################
# Merge system defaults
- name: Combine default and user defined system settings
  run_once: true
  when: system is defined
  tags: defaults
  set_fact:
    system: '{{ system_default | combine(system, recursive=True) }}'

- name: Use default system settings
  run_once: true
  when: system is not defined
  tags: defaults
  set_fact:
    system: '{{ system_default }}'

- name: Display merged system settings
  run_once: true
  when: verbose is defined and verbose == True
  tags: defaults
  debug:
    var: system

################################################################################
# Merge firewall defaults
- name: Combine default and user defined firewall settings
  run_once: true
  when: firewall is defined
  tags: defaults
  set_fact:
    firewall: '{{ firewall_default | combine(firewall, recursive=True) }}'

- name: Use default firewall settings
  run_once: true
  when: firewall is not defined
  tags: defaults
  set_fact:
    firewall: '{{ firewall_default }}'

- name: Display merged firewall settings
  run_once: true
  when: verbose is defined and verbose == True
  tags: defaults
  debug:
    var: firewall

################################################################################
# Merge security defaults
- name: Combine default and user defined security settings
  run_once: true
  when: security is defined
  tags: defaults
  set_fact:
    security: '{{ security_default | combine(security, recursive=True) }}'

- name: Use default security settings
  run_once: true
  when: security is not defined
  tags: defaults
  set_fact:
    security: '{{ security_default }}'

- name: Display merged security settings
  run_once: true
  when: verbose is defined and verbose == True
  tags: defaults
  debug:
    var: security

################################################################################
# Merge dictionaries defaults
- name: Combine default and user defined dictionaries settings
  run_once: true
  when: dictionaries is defined
  tags: defaults
  set_fact:
    dictionaries: '{{ dictionaries_default | union(dictionaries) }}'

- name: Use default dictionaries settings
  run_once: true
  when: dictionaries is not defined
  tags: defaults
  set_fact:
    dictionaries: '{{ dictionaries_default }}'

- name: Display merged dictionaries settings
  run_once: true
  when: verbose is defined and verbose == True
  tags: defaults
  debug:
    var: dictionaries

################################################################################
# Merge DNS defaults
- name: Combine default and user defined dns settings
  run_once: true
  when: dns is defined
  tags: defaults
  set_fact:
    dns: '{{ dns_default | combine(dns, recursive=True) }}'

- name: Use default DNS settings
  run_once: true
  when: dns is not defined
  tags: defaults
  set_fact:
    dns: '{{ dns_default }}'

- name: Display merged dns settings
  run_once: true
  when: verbose is defined and verbose == True
  tags: defaults
  debug:
    var: dns

################################################################################
# Merge webmail defaults
- name: Combine default and user defined webmail settings
  run_once: true
  when: webmail is defined
  tags: defaults
  set_fact:
    webmail: '{{ webmail_default | combine(webmail, recursive=True) }}'

- name: Use default webmail settings
  run_once: true
  when: webmail is not defined
  tags: defaults
  set_fact:
    webmail: '{{ webmail_default }}'

- name: Display merged webmail settings
  run_once: true
  when: verbose is defined and verbose == True
  tags: defaults
  debug:
    var: webmail


################################################################################
# Merge website defaults
- name: Combine default and user defined website settings
  run_once: true
  when: website is defined
  tags: defaults
  set_fact:
    website: '{{ website_default | combine(website, recursive=True) }}'

- name: Use default website settings
  run_once: true
  when: website is not defined
  tags: defaults
  set_fact:
    website: '{{ website_default }}'

- name: Display merged website settings
  run_once: true
  when: verbose is defined and verbose == True
  tags: defaults
  debug:
    var: website

################################################################################
# Merge backup defaults
- name: Combine default and user defined backup settings
  run_once: true
  when: backup is defined
  tags: defaults
  set_fact:
    backup: '{{ backup_default | combine(backup, recursive=True) }}'

- name: Use default backup settings
  run_once: true
  when: backup is not defined
  tags: defaults
  set_fact:
    backup: '{{ backup_default }}'

- name: Display merged backup settings
  run_once: true
  when: verbose is defined and verbose == True
  tags: defaults
  debug:
    var: backup


################################################################################
# Merge defaults development settings
- name: Combine default and user defined devel settings
  run_once: true
  when: devel is defined
  tags: defaults
  set_fact:
    devel: '{{ devel_default | combine(devel, recursive=True) }}'

- name: Use default devel settings
  run_once: true
  when: devel is not defined
  tags: defaults
  set_fact:
    devel: '{{ devel_default }}'

- name: Display merged devel settings
  run_once: true
  when: verbose is defined and verbose == True
  tags: defaults
  debug:
    var: devel

################################################################################
# Merge defaults DKIM keys settings
- name: Combine default and user defined dkim settings
  run_once: true
  when: dkim is defined
  tags: defaults
  set_fact:
    dkim: '{{ dkim_default | combine(dkim, recursive=True) }}'

- name: Use default dkim settings
  run_once: true
  when: dkim is not defined
  tags: defaults
  set_fact:
    dkim: '{{ dkim_default }}'

- name: Display merged dkim settings
  run_once: true
  when: verbose is defined and verbose == True
  tags: defaults
  debug:
    var: dkim


################################################################################
# Merge defaults DMARC keys settings
- name: Combine default and user defined dmarc settings
  run_once: true
  when: dmarc is defined
  tags: defaults
  set_fact:
    dmarc: '{{ dmarc_default | combine(dmarc, recursive=True) }}'

- name: Use default dmarc settings
  run_once: true
  when: dmarc is not defined
  tags: defaults
  set_fact:
    dmarc: '{{ dmarc_default }}'

- name: Display merged dmarc settings
  run_once: true
  when: verbose is defined and verbose == True
  tags: defaults
  debug:
    var: dmarc

################################################################################
# Merge defaults ejabberd settings
- name: Combine default and user defined ejabberd settings
  run_once: true
  when: ejabberd is defined
  tags: defaults
  set_fact:
    ejabberd: '{{ ejabberd_default | combine(ejabberd, recursive=True) }}'

- name: Use default ejabberd settings
  run_once: true
  when: ejabberd is not defined
  tags: defaults
  set_fact:
    ejabberd: '{{ ejabberd_default }}'

- name: Display merged ejabberd settings
  run_once: true
  when: verbose is defined and verbose == True
  tags: defaults
  debug:
    var: ejabberd

################################################################################
# Merge defaults bind settings
- name: Combine default and user defined bind settings
  run_once: true
  when: bind is defined
  tags: defaults
  set_fact:
    bind: '{{ bind_default | combine(bind, recursive=True) }}'

- name: Use default bind settings
  run_once: true
  when: bind is not defined
  tags: defaults
  set_fact:
    bind: '{{ bind_default }}'

- name: Display merged bind settings
  run_once: true
  when: verbose is defined and verbose == True
  tags: defaults
  debug:
    var: bind


################################################################################
# Merge defaults gogs settings
- name: Combine default and user defined gogs settings
  run_once: true
  when: gogs is defined
  tags: defaults
  set_fact:
    gogs: '{{ gogs_default | combine(gogs, recursive=True) }}'

- name: Use default gogs settings
  run_once: true
  when: gogs is not defined
  tags: defaults
  set_fact:
    gogs: '{{ gogs_default }}'

- name: Display merged gogs settings
  run_once: true
  when: verbose is defined and verbose == True
  tags: defaults
  debug:
    var: gogs


################################################################################
# Merge defaults transmission settings
- name: Combine default and user defined transmission settings
  run_once: true
  when: transmission is defined
  tags: defaults
  set_fact:
    transmission: '{{ transmission_default | combine(transmission, recursive=True) }}'

- name: Use default transmission settings
  run_once: true
  when: transmission is not defined
  tags: defaults
  set_fact:
    transmission: '{{ transmission_default }}'

- name: Display merged transmission settings
  run_once: true
  when: verbose is defined and verbose == True
  tags: defaults
  debug:
    var: transmission

################################################################################
# Merge defaults posix_groups settings
- name: Combine default and user defined posix_groups settings
  run_once: true
  when: posix_groups is defined
  tags: defaults
  set_fact:
    posix_groups: '{{ posix_groups_default | union(posix_groups) }}'

- name: Use default posix_groups settings
  run_once: true
  when: posix_groups is not defined
  tags: defaults
  set_fact:
    posix_groups: '{{ posix_groups_default }}'

- name: Display merged posix_groups settings
  run_once: true
  when: verbose is defined and verbose == True
  tags: defaults
  debug:
    var: posix_groups

################################################################################
# Merge defaults privoxy settings
- name: Combine default and user defined privoxy settings
  run_once: true
  when: privoxy is defined
  tags: defaults
  set_fact:
    privoxy: '{{ privoxy_default | combine(privoxy, recursive=True) }}'

- name: Use default privoxy settings
  run_once: true
  when: privoxy is not defined
  tags: defaults
  set_fact:
    privoxy: '{{ privoxy_default }}'

- name: Display merged privoxy settings
  run_once: true
  when: verbose is defined and verbose == True
  tags: defaults
  debug:
    var: privoxy

################################################################################
# Merge defaults tor settings
- name: Combine default and user defined tor settings
  run_once: true
  when: tor is defined
  tags: defaults
  set_fact:
    tor: '{{ tor_default | combine(tor, recursive=True) }}'

- name: Use default tor settings
  run_once: true
  when: tor is not defined
  tags: defaults
  set_fact:
    tor: '{{ tor_default }}'

- name: Display merged tor settings
  run_once: true
  when: verbose is defined and verbose == True
  tags: defaults
  debug:
    var: tor

################################################################################
# Merge defaults zabbix settings
- name: Combine default and user defined zabbix settings
  run_once: true
  when: zabbix is defined
  tags: defaults
  set_fact:
    zabbix: '{{ zabbix_default | combine(zabbix, recursive=True) }}'

- name: Use default zabbix settings
  run_once: true
  when: zabbix is not defined
  tags: defaults
  set_fact:
    zabbix: '{{ zabbix_default }}'

- name: Display merged zabbix settings
  run_once: true
  when: verbose is defined and verbose == True
  tags: defaults
  debug:
    var: zabbix

################################################################################
# Merge defaults sogo settings
- name: Combine default and user defined sogo settings
  run_once: true
  when: sogo is defined
  tags: defaults
  set_fact:
    sogo: '{{ sogo_default | combine(sogo, recursive=True) }}'

- name: Use default sogo settings
  run_once: true
  when: sogo is not defined
  tags: defaults
  set_fact:
    sogo: '{{ sogo_default }}'

- name: Display merged sogo settings
  run_once: true
  when: verbose is defined and verbose == True
  tags: defaults
  debug:
    var: sogo

################################################################################
# Marking the default settings as loaded should increase the speed of the deployment
- name: Mark the default settings as loaded
  run_once: true
  tags: defaults
  set_fact:
    defaults_loaded: true
