---
# This role load all the default values, and merge them with user specified values.
# This is a first version, roughly copy and paste, but will evolve to something more
# elaborated later. The final purpose is fulfilled:
# Users can specify copy partial branches of default values, and not worry
# about new version changes.


################################################################################
# Merge user options with default options
- name: Combine default and user defined network settings
  run_once: true
  when: network is defined
  tags: defaults
  set_fact:
    network: '{{ network_default | combine(network, recursive=True) }}'

- name: Use default network settings
  run_once: true
  when: network is not defined
  tags: defaults
  set_fact:
    network: '{{ network_default }}'

################################################################################
# Merge user options with default options
- name: Combine default and user defined mail settings
  run_once: true
  when: mail is defined
  tags: defaults
  set_fact:
    mail: '{{ mail_default | combine(mail, recursive=True) }}'

- name: Use default mail settings
  run_once: true
  when: mail is not defined
  tags: defaults
  set_fact:
    mail: '{{ mail_default }}'

################################################################################
# Merge user options with default options
- name: Combine default and user defined password settings
  run_once: true
  no_log: true
  when: passwords is defined
  tags: defaults
  set_fact:
    passwords: '{{ passwords_default | combine(passwords, recursive=True) }}'

- name: Use default passwords settings
  run_once: true
  no_log: true
  when: passwords is not defined
  tags: defaults
  set_fact:
    passwords: '{{ passwords_default }}'

################################################################################
# Merge system defaults
- name: Combine default and user defined system settings
  run_once: true
  when: system is defined
  tags: defaults
  set_fact:
    system: '{{ system_default | combine(system, recursive=True) }}'

- name: Use default system settings
  run_once: true
  when: system is not defined
  tags: defaults
  set_fact:
    system: '{{ system_default }}'

################################################################################
# Merge firewall defaults
- name: Combine default and user defined firewall settings
  run_once: true
  when: firewall is defined
  tags: defaults
  set_fact:
    firewall: '{{ firewall_default | combine(firewall, recursive=True) }}'

- name: Use default firewall settings
  run_once: true
  when: firewall is not defined
  tags: defaults
  set_fact:
    firewall: '{{ firewall_default }}'

################################################################################
# Merge security defaults
- name: Combine default and user defined security settings
  run_once: true
  when: security is defined
  tags: defaults
  set_fact:
    security: '{{ security_default | combine(security, recursive=True) }}'

- name: Use default security settings
  run_once: true
  when: security is not defined
  tags: defaults
  set_fact:
    security: '{{ security_default }}'

################################################################################
# Merge dictionaries defaults
- name: Combine default and user defined dictionaries settings
  run_once: true
  when: dictionaries is defined
  tags: defaults
  set_fact:
    dictionaries: '{{ dictionaries_default | union(dictionaries) }}'

- name: Use default dictionaries settings
  run_once: true
  when: dictionaries is not defined
  tags: defaults
  set_fact:
    dictionaries: '{{ dictionaries_default }}'

# Merge webmail defaults
- name: Combine default and user defined webmail settings
  run_once: true
  when: webmail is defined
  tags: defaults
  set_fact:
    webmail: '{{ webmail_default | combine(webmail, recursive=True) }}'

- name: Use default webmail settings
  run_once: true
  when: webmail is not defined
  tags: defaults
  set_fact:
    webmail: '{{ webmail_default }}'


################################################################################
# Merge website defaults
- name: Combine default and user defined website settings
  run_once: true
  when: website is defined
  tags: defaults
  set_fact:
    website: '{{ website_default | combine(website, recursive=True) }}'

- name: Use default website settings
  run_once: true
  when: website is not defined
  tags: defaults
  set_fact:
    website: '{{ website_default }}'

################################################################################
# Merge backup defaults
- name: Combine default and user defined backup settings
  run_once: true
  when: backup is defined
  tags: defaults
  set_fact:
    backup: '{{ backup_default | combine(backup, recursive=True) }}'

- name: Use default backup settings
  run_once: true
  when: backup is not defined
  tags: defaults
  set_fact:
    backup: '{{ backup_default }}'

################################################################################
# Merge defaults development settings
- name: Combine default and user defined devel settings
  run_once: true
  when: devel is defined
  tags: defaults
  set_fact:
    devel: '{{ devel_default | combine(devel, recursive=True) }}'

- name: Use default devel settings
  run_once: true
  when: devel is not defined
  tags: defaults
  set_fact:
    devel: '{{ devel_default }}'

################################################################################
# Merge defaults DKIM keys settings
- name: Combine default and user defined dkim settings
  run_once: true
  when: dkim is defined
  tags: defaults
  set_fact:
    dkim: '{{ dkim_default | combine(dkim, recursive=True) }}'

- name: Use default dkim settings
  run_once: true
  when: dkim is not defined
  tags: defaults
  set_fact:
    dkim: '{{ dkim_default }}'


################################################################################
# Merge defaults DMARC keys settings
- name: Combine default and user defined dmarc settings
  run_once: true
  when: dmarc is defined
  tags: defaults
  set_fact:
    dmarc: '{{ dmarc_default | combine(dmarc, recursive=True) }}'

- name: Use default dmarc settings
  run_once: true
  when: dmarc is not defined
  tags: defaults
  set_fact:
    dmarc: '{{ dmarc_default }}'

################################################################################
# Merge defaults ejabberd settings
- name: Combine default and user defined ejabberd settings
  run_once: true
  when: ejabberd is defined
  tags: defaults
  set_fact:
    ejabberd: '{{ ejabberd_default | combine(ejabberd, recursive=True) }}'

- name: Use default ejabberd settings
  run_once: true
  when: ejabberd is not defined
  tags: defaults
  set_fact:
    ejabberd: '{{ ejabberd_default }}'

################################################################################
# Merge defaults bind settings
- name: Combine default and user defined bind settings
  run_once: true
  when: bind is defined
  tags: defaults
  set_fact:
    bind: '{{ bind_default | combine(bind, recursive=True) }}'

- name: Use default bind settings
  run_once: true
  when: bind is not defined
  tags: defaults
  set_fact:
    bind: '{{ bind_default }}'


################################################################################
# Merge defaults gogs settings
- name: Combine default and user defined gogs settings
  run_once: true
  when: gogs is defined
  tags: defaults
  set_fact:
    gogs: '{{ gogs_default | combine(gogs, recursive=True) }}'

- name: Use default gogs settings
  run_once: true
  when: gogs is not defined
  tags: defaults
  set_fact:
    gogs: '{{ gogs_default }}'


################################################################################
# Merge defaults transmission settings
- name: Combine default and user defined transmission settings
  run_once: true
  when: transmission is defined
  tags: defaults
  set_fact:
    transmission: '{{ transmission_default | combine(transmission, recursive=True) }}'

- name: Use default transmission settings
  run_once: true
  when: transmission is not defined
  tags: defaults
  set_fact:
    transmission: '{{ transmission_default }}'

################################################################################
# Merge defaults posix_groups settings
- name: Combine default and user defined posix_groups settings
  run_once: true
  when: posix_groups is defined
  tags: defaults
  set_fact:
    posix_groups: '{{ posix_groups_default | union(posix_groups) }}'

- name: Use default posix_groups settings
  run_once: true
  when: posix_groups is not defined
  tags: defaults
  set_fact:
    posix_groups: '{{ posix_groups_default }}'

################################################################################
# Merge defaults privoxy settings
- name: Combine default and user defined privoxy settings
  run_once: true
  when: privoxy is defined
  tags: defaults
  set_fact:
    privoxy: '{{ privoxy_default | combine(privoxy, recursive=True) }}'

- name: Use default privoxy settings
  run_once: true
  when: privoxy is not defined
  tags: defaults
  set_fact:
    privoxy: '{{ privoxy_default }}'

################################################################################
# Merge defaults tor settings
- name: Combine default and user defined tor settings
  run_once: true
  when: tor is defined
  tags: defaults
  set_fact:
    tor: '{{ tor_default | combine(tor, recursive=True) }}'

- name: Use default tor settings
  run_once: true
  when: tor is not defined
  tags: defaults
  set_fact:
    tor: '{{ tor_default }}'

################################################################################
# Merge defaults zabbix settings
- name: Combine default and user defined zabbix settings
  run_once: true
  when: zabbix is defined
  tags: defaults
  set_fact:
    zabbix: '{{ zabbix_default | combine(zabbix, recursive=True) }}'

- name: Use default zabbix settings
  run_once: true
  when: zabbix is not defined
  tags: defaults
  set_fact:
    zabbix: '{{ zabbix_default }}'

################################################################################
# Merge defaults sogo settings
- name: Combine default and user defined sogo settings
  run_once: true
  when: sogo is defined
  tags: defaults
  set_fact:
    sogo: '{{ sogo_default | combine(sogo, recursive=True) }}'

- name: Use default sogo settings
  run_once: true
  when: sogo is not defined
  tags: defaults
  set_fact:
    sogo: '{{ sogo_default }}'

################################################################################
# Merge defaults access_check settings
- name: Combine default and user defined access_check settings
  run_once: true
  when: access_check is defined
  tags: defaults
  set_fact:
    access_check: '{{ access_check_default | combine(access_check, recursive=True) }}'

- name: Use default access_check settings
  run_once: true
  when: access_check is not defined
  tags: defaults
  set_fact:
    access_check: '{{ access_check_default }}'

################################################################################
# Merge defaults backup settings
- name: Combine default and user defined backup settings
  run_once: true
  when: backup is defined
  tags: defaults
  set_fact:
    backup: '{{ backup_default | combine(backup, recursive=True) }}'

- name: Use default backup settings
  run_once: true
  when: backup is not defined
  tags: defaults
  set_fact:
    backup: '{{ backup_default }}'

################################################################################
# Filter settings for distribution specific parameters
- name: Filter out TLSv1.3 for Debian 9 (stretch)
  run_once: true
  when:
    - ansible_facts['distribution'] == "Debian"
    - ansible_facts['distribution_major_version'] == "9"
  set_fact:
    security: '{{ security
                | combine({
                    "tls": {
                      "versions": security.tls.versions
                                | reject("eq", "TLSv1.3")
                                | list
                    }
                  }, recursive=True) }}'

################################################################################
# Marking the default settings as loaded should increase the speed of the deployment
- name: Mark the default settings as loaded
  run_once: true
  tags: defaults
  set_fact:
    defaults_loaded: true
