---

- name: Install the required packages
  tags: apt
  apt:
    update_cache: true
    name: '{{ packages }}'
    state: present

- name: Create dropbear log folder
  file:
    path: /var/log/dropbear
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Copy the ssh public key for authentication
  notify: Update initramfs
  copy:
    src: /root/.ssh/authorized_keys
    dest: /etc/dropbear-initramfs/authorized_keys
    remote_src: yes

# FIXME: The key conversion does not work anymore on Buster
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=955384
# For now, I copy the default keys
- name: List dropbear keys
  register: keys_list
  find:
    path: /etc/dropbear
    pattern: '*key'

- name: Remove dropbear default keys
  notify: Update initramfs
  copy:
    src: '{{ key.path }}'
    dest: '/etc/dropbear-initramfs/{{ key.path | basename }}'
    remote_src: true
  with_items: '{{ keys_list.files }}'
  loop_control:
    loop_var: key
